services:
  # 1. Base de Datos Relacional (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: unl_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infraestructura/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  # 2. Broker MQTT para Telemetría IoT (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:1.6
    container_name: unl_mqtt_broker
    restart: always
    ports:
      - "1884:1883"     # Puerto para la comunicación del ESP32
      - "9003:9001"     # Puerto para WebSockets
    volumes:
      - ./infraestructura/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./infraestructura/mosquitto/data:/mosquitto/data
      - ./infraestructura/mosquitto/log:/mosquitto/log

  # 3. Almacenamiento de Objetos Multimedia (MinIO)
  minio:
    image: minio/minio:latest
    container_name: unl_minio_storage
    restart: always
    ports:
      - "9005:9000"     # Puerto de la API de MinIO
      - "9002:9001"     # Consola Web de administración
    env_file:
      - ./backend/ms_eventos/.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


  # Nuevo contenedor que crea el bucket y le da permisos públicos, luego se apaga
  minio-init:
    image: minio/mc
    container_name: unl_minio_init
    depends_on:
      - minio
    env_file:
      - ./backend/ms_eventos/.env    # <-- También inyectamos las variables aquí
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      mc mb myminio/$$MINIO_BUCKET_NAME --ignore-existing;
      mc anonymous set download myminio/$$MINIO_BUCKET_NAME;
      exit 0;
      "
  # 4. Microservicio de Identidad (Login, Registro, Roles)
  ms-gestion-usuarios:
    build:
      context: ./backend/ms_gestion_usuarios
      dockerfile: Dockerfile
    container_name: unl_ms_gestion_usuarios
    restart: always
    # Se agrega asyncpg a las instalaciones en caliente para conectar con PostgreSQL de forma asíncrona
    command: >
      sh -c "pip install --no-cache-dir --break-system-packages --upgrade email-validator==2.1.1 fastapi-mail==1.4.1 dnspython==2.6.1 asyncpg && 
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend/ms_gestion_usuarios/app:/app/app
    env_file:
      - ./backend/ms_gestion_usuarios/.env
    depends_on:
      - db

  # 5. Microservicio de Telemetría (ESP32-CAM, IoT)
  ms-clima:
    build:
      context: ./backend/ms_clima
      dockerfile: Dockerfile
    container_name: unl_ms_clima
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/ms_clima/app:/app/app
    env_file:
      - ./backend/ms_clima/.env
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
    depends_on:
      - db
      - mqtt-broker

  # 6. Microservicio de Eventos (Gestión de Eventos y Notificaciones)
  ms-eventos:
    build: 
      context: ./backend/ms_eventos 
      dockerfile: Dockerfile
    container_name: unl_ms_eventos
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8002:8000" # Exposición directa para pruebas puenteando a Kong
    volumes:
      - ./backend/ms_eventos/app:/app/app 
    env_file:
      - ./backend/ms_eventos/.env    # <-- Apuntamos a tu nuevo archivo seguro
    depends_on:
      - db 

  # 7. API Gateway (Kong)
  api-gateway:
    image: kong:3.4-ubuntu
    container_name: unl_api_gateway
    restart: always
    environment:
      KONG_DATABASE: "off"          # Modo DB-less
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_CLIENT_MAX_BODY_SIZE: 5m
    ports:
      - "8000:8000"  # Puerto expuesto para el Frontend
      - "8001:8001"  # Puerto de administración de Kong
    volumes:
      - ./infraestructura/kong/kong.yml:/kong/declarative/kong.yml
    depends_on:
      - ms-gestion-usuarios
      - ms-clima
      - ms-eventos

  # 8. Frontend Web (React + Nginx)
  frontend-web:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: /api
        VITE_GOOGLE_CLIENT_ID: 883175682519-tv0t5ndf3185sdimdjd6ro9hack12m7r.apps.googleusercontent.com
        VITE_WEATHER_API_KEY: 55XRUAGTP4TFSKN476BELXZDD
    container_name: unl_frontend_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data:
  mosquitto_data:
  minio_data: