
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: unl-cloud-connect
data:
  init.sh: |
    #!/bin/bash
    set -e
    # Script para crear las 3 bases de datos al iniciar el contenedor
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
        CREATE DATABASE db_usuarios;
        CREATE DATABASE db_clima;
        CREATE DATABASE db_eventos;
    EOSQL
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unl-postgres
  namespace: unl-cloud-connect
  labels:
    app: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secrets
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sh
          subPath: init.sh
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: unl-cloud-connect
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
  type: ClusterIP
